# Generated by Django 5.2 on 2025-12-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
