# Generated by Django 5.2 on 2025-12-10 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazars', '0003_remove_place_price_remove_place_product_placeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='qr_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bazars.qrcode'),
        ),
    ]
