# Generated by Django 5.2 on 2025-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazars', '0004_alter_place_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazar',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bazar',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bazar',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bazar',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
