# Generated by Django 5.2 on 2025-12-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazars', '0005_bazar_name_en_bazar_name_ru_bazar_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bazars.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
