# Generated by Django 5.2 on 2025-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazars', '0008_alter_bazaradmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazar',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bazar',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
