# Generated by Django 5.2 on 2025-12-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_subcategory_product_subcategory'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.file'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.file'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.file'),
        ),
    ]
